apiVersion: v1
kind: ConfigMap
metadata:
  namespace: hello
  name: hello-go
data:
  application-config: |
    template: Hello, %s!
    defaultName: Stranger
  opentelemetry-config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch/metrics:
        timeout: 60s
      batch/traces:
        timeout: 1s
        send_batch_size: 50
    exporters:
      otlp:
        endpoint: opentelemetry-collector.opentelemetry.svc.cluster.local:55680
        insecure: true
    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch/metrics]
          exporters: [otlp]
        traces:
          receivers: [otlp]
          processors: [batch/traces]
          exporters: [otlp]
