apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hello
  name: hello-go
  labels:
    app: hello-go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-go
  template:
    metadata:
      labels:
        app: hello-go
    spec:
      containers:
      - name: hello-go
        env:
        - name: OTEL_EXPORTER
          value: otlp
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.namespace=hello,service.name=hello-go,service.version=v2021.01.0
        image: docker.pkg.github.com/jmgrimes/hello-go/hello-go:v2021.01.0
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /hello-world
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        ports:
        - name: service-http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /hello-world
            port: 8080
        resources:
          limits:
            memory: 512Mi
            cpu: 512m
          requests:
            memory: 128Mi
            cpu: 256m
        volumeMounts:
        - name: application-config
          mountPath: /app/conf
      - name: opentelemetry-collector
        image: otel/opentelemetry-collector:0.17.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 512Mi
            cpu:  256m
          requests:
            memory: 32Mi
            cpu: 32m
        volumeMounts:
        - name: opentelemetry-config
          mountPath: /etc/otel
      imagePullSecrets:
        - name: registry-credentials
      volumes:
      - name: application-config
        configMap:
          name: hello-go
          items:
          - key: application-config
            path: application.yaml
      - name: opentelemetry-config
        configMap:
          name: hello-go
          items:
          - key: opentelemetry-config
            path: config.yaml