apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hello
  name: hello-java
  labels:
    app: hello-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-java
  template:
    metadata:
      labels:
        app: hello-java
    spec:
      containers:
      - name: hello-java
        env:
          - name: OTEL_EXPORTER
            value: otlp
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: service.namespace=hello,service.name=hello-java,service.version=v2021.01.3
        image: docker.pkg.github.com/jmgrimes/hello-java/hello-java:v2021.01.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 30
        ports:
        - name: service-http
          containerPort: 8080
        - name: admin-http
          containerPort: 8081
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8081
        resources:
          requests:
            memory: 128Mi
            cpu: 256m
          limits:
            memory: 512Mi
            cpu: 512m
        volumeMounts:
        - name: application-config
          mountPath: /app/conf
      - name: opentelemetry-collector
        image: otel/opentelemetry-collector:0.17.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 512Mi
            cpu:  256m
          requests:
            memory: 32Mi
            cpu: 32m
        volumeMounts:
        - name: opentelemetry-config
          mountPath: /etc/otel
      imagePullSecrets:
        - name: registry-credentials
      volumes:
      - name: application-config
        configMap:
          name: hello-java
          items:
          - key: application-config
            path: application.yaml
      - name: opentelemetry-config
        configMap:
          name: hello-java
          items:
          - key: opentelemetry-config
            path: config.yaml