apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-otel-sidecar
  namespace: hello
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
          
    processors:
      batch/traces:
        timeout: 1s
        send_batch_size: 50
      batch/metrics:
        timeout: 60s

    exporters:
      logging:
        loglevel: debug

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch/traces]
          exporters: [logging]
        metrics:
          receivers: [otlp]
          processors: [batch/metrics]
          exporters: [logging]