apiVersion: v1
kind: Service
metadata:
  namespace: opentelemetry
  name: opentelemetry-collector
spec:
  selector:
    app: opentelemetry-collector
  ports:
    - protocol: TCP
      port: 55680
      targetPort: 55680