apiVersion: v1
kind: ConfigMap
metadata:
  namespace: opentelemetry
  name: opentelemetry-collector
data:
  opentelemetry-config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch/metrics:
        timeout: 60s
      batch/traces:
        timeout: 1s
        send_batch_size: 50
    exporters:
      logging:
        loglevel: debug
    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch/metrics]
          exporters: [logging]
        traces:
          receivers: [otlp]
          processors: [batch/traces]
          exporters: [logging]